## In this model we will be performing the feature engineering.

In [2]:
### Libraries we will be using 

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
## Dataset we will be using 

data = pd.read_csv('../Datasets/cleaned.csv')
data.drop(columns=['Unnamed: 0','customerID'], inplace=True)
data.head(5)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
### Analyzing the data types of each feature

print(data.dtypes)

gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

### We have to convert all the columns with str dtype to either integer or float.

In [5]:
strdtypes = data.select_dtypes('str')
for col in strdtypes.columns:
    print(col, '->', strdtypes[col].unique())

gender -> <StringArray>
['Female', 'Male']
Length: 2, dtype: str
Partner -> <StringArray>
['Yes', 'No']
Length: 2, dtype: str
Dependents -> <StringArray>
['No', 'Yes']
Length: 2, dtype: str
PhoneService -> <StringArray>
['No', 'Yes']
Length: 2, dtype: str
MultipleLines -> <StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
InternetService -> <StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
OnlineSecurity -> <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
OnlineBackup -> <StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
DeviceProtection -> <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
TechSupport -> <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
StreamingTV -> <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
StreamingMovies -> <StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
Contract -> <StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
PaperlessBilling -> <StringArray>
['Yes', 'No']
Length: 2, dtype: str
PaymentMethod -> <StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
Churn -> <StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [6]:
### Converting each column 
data['gender'] = data['gender'].map({'Male':1,'Female':0})

## Columns with yes or no values 
yncolumns = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn']

for each in yncolumns:
    data[each] = data[each].map({'Yes':1,'No':0})

## We have plotted all the yes and no values to 1 and 0 

## Columns with yes,no,nointernetservice

ynncolumns = ['MultipleLines', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport','StreamingTV', 'StreamingMovies']

for each in ynncolumns:
    data[each] = data[each].apply(lambda x: 1 if x == 'Yes' else 0)


### Payment method 

mapping_payment = {'Electronic check':0, 'Mailed check':1,'Bank transfer (automatic)':2,   'Credit card (automatic)':3  }

data['PaymentMethod'] = data['PaymentMethod'].map(mapping_payment)

## Converting the Contract 

mapping_contract = {'Month-to-month':0, 'One year':1, 'Two year':2 }
data['Contract'] = data['Contract'].map(mapping_contract)

### Converting the Internet Service

mapping_internet = {'DSL':0, 'Fiber optic':1, 'No':2}
data['InternetService'] = data['InternetService'].map(mapping_internet)

In [7]:
### Checking the dtypes of all the columns
print(data.dtypes)

gender                int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines         int64
InternetService       int64
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingTV           int64
StreamingMovies       int64
Contract              int64
PaperlessBilling      int64
PaymentMethod         int64
MonthlyCharges      float64
TotalCharges        float64
Churn                 int64
dtype: object

### We have successfully converted all the string data types to integers
---

In [8]:
### Lets check if the newly created binary dataset has any Null values 

print(data.isna().sum())

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

### There are no null values in the binary dataset, which is a poisitve sign for model deployment.

---
### Lets check the correlation between the columns

In [9]:
correlated_matrix = data.corr()
correlated_matrix.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
gender,1.000000,-0.001819,-0.001379,0.010349,0.005285,-0.007515,-0.008883,-0.002236,-0.016328,-0.013093,-0.000807,-0.008507,-0.007124,-0.010105,0.000095,-0.011902,-0.004928,-0.013779,0.000048,-0.008545
SeniorCitizen,-0.001819,1.000000,0.016957,-0.210550,0.015683,0.008392,0.142996,-0.032160,-0.038576,0.066663,0.059514,-0.060577,0.105445,0.119842,-0.141820,0.156258,-0.093712,0.219874,0.102411,0.150541
Partner,-0.001379,0.016957,1.000000,0.452269,0.381912,0.018397,0.142561,0.000513,0.143346,0.141849,0.153556,0.120206,0.124483,0.118108,0.294094,-0.013957,0.133280,0.097825,0.319072,-0.149982
Dependents,0.010349,-0.210550,0.452269,1.000000,0.163386,-0.001078,-0.024307,0.044030,0.080786,0.023639,0.013900,0.063053,-0.016499,-0.038375,0.240556,-0.110131,0.124002,-0.112343,0.064653,-0.163128
tenure,0.005285,0.015683,0.381912,0.163386,1.000000,0.007877,0.332399,-0.029835,0.328297,0.361138,0.361520,0.325288,0.280264,0.285402,0.676734,0.004823,0.340939,0.246862,0.825880,-0.354049

In [10]:
### Upper triangular matrix to reduce the duplicate values 
upper = correlated_matrix.where(np.triu(np.ones(correlated_matrix.shape), k =1 ).astype(bool))

### Now lets check the highly correlated columns

In [11]:
high_correlated_features = [column for column in upper.columns if any(upper[column] > 0.95)]
print(high_correlated_features)

[]

### We figured out that no columns are highly correlated, which concludes that every column has its own significance.

---
### Variance in the data

In [12]:
### Checking the variance in the data 
only_numerical = data.select_dtypes(include=['int64', 'float64'])
variance = only_numerical.var()

### Lets check if any of the columns are less varied

print(variance[variance <= 0.05]) ## Variance less than 5%

Series([], dtype: float64)

### As we can see that every column are varied, which suggests that there is variation in the data

---

### Checking the skewness of the data

In [13]:
selected_columns = data.drop(columns=['Churn'])
only_numeric_selected = selected_columns.select_dtypes(include=['int64', 'float64'])
skewed_data = only_numeric_selected.skew()
print(skewed_data)
### As seen there is no such skewness in the data

gender             -0.018776
SeniorCitizen       1.831103
Partner             0.070024
Dependents          0.880908
tenure              0.237731
PhoneService       -2.729727
MultipleLines       0.316232
InternetService     0.205704
OnlineSecurity      0.944373
OnlineBackup        0.652954
DeviceProtection    0.657594
TechSupport         0.925245
StreamingTV         0.475441
StreamingMovies     0.458191
Contract            0.635149
PaperlessBilling   -0.377503
PaymentMethod       0.218108
MonthlyCharges     -0.222103
TotalCharges        0.961642
dtype: float64

In [15]:
### Exporting the dataset in form of csv 
data.to_csv('../Datasets/formodel.csv')

### Thats the end of the whole feature engineering